[TEMP] common.mk: Disable compressed APEX
sonyxperiadev/device-sony-common pull request #871
Opened 2021-11-04 16:44 UTC by Haxk20

As a temp fix lets disable compressed APEX which causes a12 to not boot on
4.14 kernel.

Please test !!!!!

2021-11-04 16:45 UTC, MarijnS95 commented on common.mk
> +ifneq ($(filter 4.14, $(SOMC_KERNEL_VERSION)),)
```suggestion
ifeq ($(SOMC_KERNEL_VERSION), 4.14)
```

Work smarter, not harder.

2021-11-10 08:30 UTC, mdsohail99 commented
> As a temp fix lets disable compressed APEX which causes a12 to not boot on 4.14 kernel.
> 
> Please test !!!!!

Hi brother I am noob to developing, can you please tell me or guide me how to do that. Thanks.

2021-11-10 19:41 UTC, ShujathMohd requested changes
The flag should be declared immediately/after the inheritance of updatable_apex.mk which is in platform.
By declaring here the flag t is getting overriden/ignored.

2021-11-10 19:46 UTC, bartcubbins commented
or we can set it with OVERRIDE_PRODUCT_COMPRESSED_APEX flag

2021-11-10 19:46 UTC, MarijnS95 commented
`OVERRIDE_PRODUCT_COMPRESSED_APEX` works fine for me, no idea why this wasn't tested.

2021-11-11 00:32 UTC, Haxk20 commented
Because my pdx201 rebooted once i wiped data. And i didnt get to it yet.
Thus has test please with lot of !

2021-11-11 19:14 UTC, MarijnS95 commented
> Because my pdx201 rebooted

No need to submit PRs if you know your solution doesn't resolve the issue :)

2021-12-08 07:56 UTC, closed without merging