[R] common-treble: use GPT-based IBootControl 1.0 HAL for lena
sonyxperiadev/device-sony-common pull request #879
Opened 2022-01-20 11:53 UTC by sledges

2022-01-20 11:55 UTC, MarijnS95 commented
> No description provided

Maybe explain the gpt vs misc difference in the 1.0 and 1.1 default hap in a comment and the commit body?

2022-01-20 12:02 UTC, MarijnS95 requested changes

2022-01-20 12:02 UTC, MarijnS95 commented on common-treble.mk
> +    android.hardware.boot@1.0-service
I remember that the 1.1 service can start the 1.1 and 1.0 passthrough. Perhaps we only need to select on the -impl for Lena.

Then you can remove the vintf workaround as well.

2022-01-20 12:02 UTC, MarijnS95 commented on common-treble.mk
> +    android.hardware.boot@1.0-service
https://android.googlesource.com/platform/hardware/interfaces/+/refs/tags/android-11.0.0_r46/boot/1.1/default/service.cpp#26 fwiw.

2022-01-21 13:34 UTC, sledges commented
Superseded by #880.

2022-01-21 13:34 UTC, closed without merging